import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ModalProvider, QueryProvider ,ThemeProvider} from "./providers";
import RootLayoutWrapper from "./_components/RootLayoutWrapper";
import { Toaster } from "@/components/ui/sonner";
import { Header } from "@/components/shared";

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`antialiased ${geistSans.variable} ${geistMono.variable} font-sans ${figtree.variable}`}
    >
      <body>
        
        <QueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange={false}
          >
            <ModalProvider>
              <RootLayoutWrapper>           
                {children}   
              </RootLayoutWrapper>
              
            </ModalProvider>
            <Toaster />

          </ThemeProvider>
        </QueryProvider>

      </body>
    </html>
  );
}
